### ISSUE TITLE
Download PDF

### ISSUE THREAD

**Issue by raffaelemancuso** [J-E-J-S/pyminer#23]
Is it / will be possible to download the PDF of the papers?

**Comment by J-E-J-S** [comment]
I can make this a feature although you might be more interested in looking into the getpapers cli that the paper retrieval function is built on: https://github.com/ContentMine/getpapers
Retrieving the full xml or pdf is possible here. Let me know though if you think it would still be useful for this application.

**Comment by raffaelemancuso** [comment]
> I can make this a feature although you might be more interested in looking into the getpapers cli that the paper retrieval function is built on: https://github.com/ContentMine/getpapers Retrieving the full xml or pdf is possible here. Let me know though if you think it would still be useful for this application.

The problem is that that software seems abandoned, and I can't get it to work anyway (it retrieves another paper than the one I'm asking for)

**Comment by J-E-J-S** [comment]
It's not meant for retrieving specific papers, it will query the EUPMC database based on a search term. It does have some flaws and is outdated to the current API though. What do you have in mind for your purpose?

**Comment by raffaelemancuso** [comment]
I have a list of DOIs and I have to download the papers for the journals I'm subscribed to.

For the ones I don't have a subscription, then nothing.

**Comment by J-E-J-S** [comment]
So I am assuming this is across both open source and closed journals? The problem with EUPMC is that it will only give you non-pay walled articles, if you want to be able to access any article in any journal you may have to look at the individual APIs offered by journals e.g. Springer Nature https://www.springernature.com/gp/researchers/text-and-data-mining or perhaps scihub https://scihub.copernicus.eu/twiki/do/view/SciHubWebPortal/APIHubDescription. 

The getpapers function is not built for retrieving individual papers in any case, so it would be best to look elsewhere.

**Comment by raffaelemancuso** [comment]
> So I am assuming this is across both open source and closed journals?

Yes

> if you want to be able to access any article in any journal you may have to look at the individual APIs offered by journals e.g. Springer Nature https://www.springernature.com/gp/researchers/text-and-data-mining or perhaps scihub https://scihub.copernicus.eu/twiki/do/view/SciHubWebPortal/APIHubDescription.

Thank you very much.

Do you know of any wrapper around those APIs?

I mean, do you know of any software that allows me to download the PDF of scientific articles, both for open access and paywalled article (if I'm subscribed to the journal)?

> The getpapers function is not built for retrieving individual papers in any case, so it would be best to look elsewhere.

By the `getpapers` function, do you mean the one of `pyminer` or the one of `ContentMine/getpapers`?

**Comment by J-E-J-S** [comment]
I am afraid I don't know any wrappers for these APIs but I'd say give it a shot of making your own - they normally have quite good documentation. I don't know of any software which will do this all for you, I imagine its a nightmare of authorization unless shibboleth or openathens has something like this. The biggest project I know of trying to collate all papers is open alex which might interest you https://openalex.org/ which I believe is trying to get over this hurdle of closed access papers for mining. 

I wrote pyminer as an extension of content mines getpapers so it explicitly calls that function during the search.

**Comment by raffaelemancuso** [comment]
Thank you very much for the valuable informations!
